### PR TITLE
Feature exception handling

### PR DESCRIPTION
**Pull request by florian98765**
Make Cython C-Function return -1 error code on internal exceptions. Otherwise internal execptions are ignored and not passed on to the calling python function. 

NOTE: code was tested for CV_WrapPrecSetupFunction.evaluate() and CV_WrapRhsFunction.evaluate(), but it should work also for the rest. 

greetings 
Florian

### CODE REVIEW

**Comment by florian98765** [comment]
hello,
i was just looking at #26. If any C-Function may return -1 as a legal return value, it would be better to use "except? -1" instead of "except -1". In this case Cython additionally calls PyErr_Occurred() if -1 is returned, to make sure a "real" exception has occured. 

greetings Florian

**Comment by bmcage** [comment]
It would indeed be best to merge this with #26, like this users can return -1 also as per the docs of SUNDIALS. If we only take this approach, users must raise exception, which generates the -1 via except here.
@aragilar what is your opinion? Both approaches must be possible?

**Comment by aragilar** [comment]
Sundials has different results depending on whether the return value is positive (func failed, try again) or negative (func failed, exit), so we need both. But catching exceptions and making them fail immediately seems like the best idea (errors found faster and try/except can be used to return the right value).

**Comment by bmcage** [comment]
@florian98765 @aragilar 
Ok, one of you wants to merge the two PR into one that is compatible and with `except? `instead of `except` ?
Test code with return value positive, 0 and  -1 in, and with an exception occurring, would be needed to. I'm prepared to add to IDA if cvode changes are definitive.

**Comment by aragilar** [comment]
I've nearly got #27 and #26 merged and done, just need to finish some more tests.

**Comment by bmcage** [comment]
@aragilar You had time for this? If you open a new PR with the merge, I can go over what you already have.

**Comment by aragilar** [comment]
I plan on finishing this on the weekend (testing without tox was slowing things down, which was why I added it)

**Comment by aragilar** [comment]
This can be closed now, as it was part of #36 (which has been merged).

**Pull request closed without merging**
