### PR TITLE
Convert to sundials version 3.1.1 

### PR DESCRIPTION
**Pull request by bmcage**
This PR is not finished, but can start to be tested by more people.

Note: at the moment, sundials must be build with int32 index type:

    cmake -DLAPACK_ENABLE=ON -DSUNDIALS_INDEX_TYPE=int32_t ../../sundials-3.1.1/

This is needed to have lapack included, required by our code. Default of index type is int64.

TODO: 
* Missing LAPACK symbols ??
* _jacdense is off, convert SUNMATRIX for use ??
* except? -1needs to be removed on jacdense in IDA. Why not in CVODE?
* signatures changed of some functions, add conversion part in doc ?
* convert example code, add extra example code
* for compilation, can we on build test on SUNDIALS_INDEX_TYPE, and if int64 disable all lapack code in an easy manner ?

### CODE REVIEW

**Comment by bmcage** [comment]
@aragilar James, I could use some help finalizing this PR. With the changes here, all compiles and installs. However, not working yet with undefined symbol. 
It seems to me lapack will be more and more problematic. Ideally we can build only optionally with lapack, based on your method to set DTYPE. But I don't fully understand how the pxi works. 

You have some time to investigate how best to work and compile with lapack?

**Comment by aragilar** [comment]
I've made some progress, I've got the multiple index types stuff set up, and fixed the undefined symbol problem (we need to link to more libraries now). There's something wrong with the jacobian setup for cvode, and there's something wrong with prec_setupfn for ida. I'll try to look at that tomorrow (well today since it's after midnight here ;)

**Comment by bmcage** [comment]
Great to hear. I have time Thursday forenoon to continue myself. Push it to a clone of the branch and I can obtain your version (if PR agains my branch is possible, even better). 
Didn't look now, in case you mean setting dense Jacobian not working, that I deactivated, so will not work. The method now expects a 'SUNMatrix', but  our method creates a Dlsmat, so I commented out the line in cvode and ida that does:

    ndarray2DlsMatd(Jac, jac_tmp)

We need to find some way to assume a dense matrix, but cast it to 'SUNMatrix' I assume. Not sure how to go about that. The methods in common_defs.pyx on matrixes might need changing to SUNMatrix? Or consider some specific implementations like DlsMat? This is code we inherited from the original pysundials code, never worked with it and not using dense matrices myself...

**Comment by bmcage** [comment]
ok, my tests were also successfull, except the fortran parts with module loading not working, but as the tests here work, I'll leave it like that, a clean install would be needed. 
You mentioned: all ok, "apart from the 32bit float tests that we still need to fix". I remember vaguely something about this from before the summer, but now don't remember exactly what it was. What was that about again, and should it hold up a release?

**Comment by bmcage** [comment]
Changed Jacobian call to residual, cj, as it is in sundials. I would merge in master if no open issues on your side

**Pull request merged**
