### PR TITLE
Update paper author info

### PR DESCRIPTION
**Pull request by aragilar**
@c-abird @florian98765 @logicabrity Is you affiliation correct (if not can you please comment so we can fix it).
@pplk @logicabrity Do you have an ORCID (https://orcid.org/)?

### CODE REVIEW

**Comment by c-abird** [comment]
Perfect, thanks for adding

**Comment by florian98765** [comment]
My affiliation (Florian Bruckner) should be changed to "University of Vienna".
Thanks.

**Comment by aragilar** [comment]
I've updated @florian98765 affiliation in #65.

**Comment by logicabrity** [comment]
It’s correct. Thanks for adding. No ORCID though.

**Pull request merged**
