### PR TITLE
Use doctr to build apidocs

### PR DESCRIPTION
**Pull request by aragilar**
This is the second last part of getting the API docs to be built correctly. We use doctr (https://drdoctr.github.io/doctr/) to build the API docs on travis, which are then uploaded to the gh-pages branch.

The travis run probably won't pass, as there a few things which need to be modified. @bmcage Can you rerun `doctr configure`, and remove the key associated with my repo. Once this is done, I'll make a PR against the new gh-pages branch to add the last bits, and then everything should hopefully just work.

To see how this will be rendered, see https://aragilar.github.io/odes/dev/.

### CODE REVIEW

**Comment by bmcage** [comment]
Should github_deploy_key_aragilar_odes.enc be part of the commit files ?

**Comment by bmcage** [comment]
ok, I see the .enc is needed. The output of configure also says:

  Add these lines to your `.travis.yml` file:

    script:
      - set -e
      - # Command to build your docs
      - pip install doctr
      - doctr deploy --built-docs path/to/built/html/ <target-directory>

I suppose that is what still is to do.

**Comment by bmcage** [comment]
James, I added you as collaborator. That should allow you to do the final touches to this PR directly. There is not much review involved for this, we just need to have the doc building working. 

You have proven in the past to know the code base very well, doing multiple PR. Just give me a heads up if you work on a feature via an issue or PR.

**Comment by aragilar** [comment]
@bmcage Apparently pushing a gh-pages branch to a repository sometimes doesn't automatically tell github to use that branch to show. Can you publish the gh-pages branch as per https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages.

**Comment by bmcage** [comment]
The setting was on gh-pages: 
afbeelding

I'm unsure as what to do. Should it be from master instead?

**Comment by bmcage** [comment]
I changed to master once, and then back to gh-pages.

I see the remark: Your site is ready to be published at http://bmcage.github.io/odes/.  

Not sure now if that will be automatic, or if I need to press another button somewhere.

**Comment by bmcage** [comment]
I now obtain: 
afbeelding

but in reality I still obtain a 404 ....

**Comment by aragilar** [comment]
It looks like it's working now...

**Comment by bmcage** [comment]
Great. Let's see with the first change if it propagates correctly!

**Pull request merged**
