### PR TITLE
remove alen from imports

### PR DESCRIPTION
**Pull request by tinosulzer**
Newest version of `numpy` errors when `alen` is imported, see for example https://github.com/pybamm-team/PyBaMM/runs/7017620061?check_suite_focus=true#step:11:28

This PR removes `alen` from the python imports, and replaces `alen` with `len` where appropriate

### CODE REVIEW

**Comment by tinosulzer** [comment]
I don't know why the tests are failing, is it because of the change I made?

**Comment by aragilar** [comment]
@tinosulzer No, it looks fine to me. Thanks for fixing this.

**Comment by tinosulzer** [comment]
Thanks for the quick review. Will there be a new release soon, or should we change to pip install from master for now?

**Comment by aragilar** [comment]
Uploaded to PyPI now.

**Pull request merged**
