### PR TITLE
Sundials 4 1 support

### PR DESCRIPTION
**Pull request by bmcage**
These changes start doing the change to sundials version 4.1 fixing #98 
Further testing needed.

### CODE REVIEW

**Comment by bmcage** [comment]
@aragilar Any idea what the tox error could be in https://travis-ci.org/bmcage/odes/jobs/575787784 ? 
Seems inline statements gives errors now also in the 3.x travis build, I'll look at that thursday

**Comment by aragilar** [comment]
There's some kind of unicode issue? Not sure why though, I'll look into it.

**Comment by bmcage** [comment]
@aragilar I finished cythonizing new parts for cvode. Compiling errors next to fix, then ida.

I obtained errors on except -1 functions no longer assigning I could not figure out. Those giving cython error removed now for this reason. Just so you know I reverted some of these.

**Comment by bmcage** [comment]
@aragilar I believe I have fixed all issues, tests passing (except extended py37 it seems, but not default code type).

Default is now however double precision and index type 64, the same as sundials proper, so  `-DSUNDIALS_INDEX_SIZE=32` required (or the deprecated `-DSUNDIALS_INDEX_TYPE=int32_t`) when compiling sundials to have same behavior. 

Please test with your code, so as to have as complete test as possible before release.

**Comment by flokli** [comment]
I pointed the scikits-odes derivation to the latest commit in that series (e2e2e072cb3741d7268532be43221671913493b9), and passed in sundials 4.1.0, and tests passed on Python 2.7, 3.6 and 3.7:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.16, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: /nix/store/r80dk0hcian3s08hs8zwj328i6422wx1-python2.7-scikits.odes-2.4.0-9-g93075ae/lib/python2.7/site-packages/scikits/odes/tests
collected 81 items

test_dae.py ....                                                         [  4%]
test_dop.py .                                                            [  6%]
test_get_info.py .....                                                   [ 12%]
test_odeint.py .....                                                     [ 18%]
test_on_funcs.py ............                                            [ 33%]
test_on_funcs_ida.py ............                                        [ 48%]
test_user_return_vals_cvode.py ........................                  [ 77%]
test_user_return_vals_ida.py ..................                          [100%]

=============================== warnings summary ===============================
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
  /nix/store/r80dk0hcian3s08hs8zwj328i6422wx1-python2.7-scikits.odes-2.4.0-9-g93075ae/lib/python2.7/site-packages/scikits/odes/dae.py:389: DeprecationWarning: Old api is deprecated, move to new api
    return self._integrator.init_step(t0, y0, yp0, y_ic0_retn, yp_ic0_retn)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 81 passed, 9 warnings in 1.21 seconds =====================
```

```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.1.0, py-1.8.0, pluggy-0.12.0
rootdir: /nix/store/qynjaj1mi41b8gsi3wml6lq8qwpwl6vv-python3.6-scikits.odes-2.4.0-9-g93075ae/lib/python3.6/site-packages/scikits/odes/tests
collected 81 items

test_dae.py ....                                                         [  4%]
test_dop.py .                                                            [  6%]
test_get_info.py .....                                                   [ 12%]
test_odeint.py .....                                                     [ 18%]
test_on_funcs.py ............                                            [ 33%]
test_on_funcs_ida.py ............                                        [ 48%]
test_user_return_vals_cvode.py ........................                  [ 77%]
test_user_return_vals_ida.py ..................                          [100%]

=============================== warnings summary ===============================
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
  /nix/store/qynjaj1mi41b8gsi3wml6lq8qwpwl6vv-python3.6-scikits.odes-2.4.0-9-g93075ae/lib/python3.6/site-packages/scikits/odes/dae.py:389: DeprecationWarning: Old api is deprecated, move to new api
    return self._integrator.init_step(t0, y0, yp0, y_ic0_retn, yp_ic0_retn)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================== 81 passed, 9 warnings in 1.61s ========================

```

```
============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-5.1.0, py-1.8.0, pluggy-0.12.0
rootdir: /nix/store/n76280az9qbrssvkyqx5zka53asdasni-python3.7-scikits.odes-2.4.0-9-g93075ae/lib/python3.7/site-packages/scikits/odes/tests
collected 81 items

test_dae.py ....                                                         [  4%]
test_dop.py .                                                            [  6%]
test_get_info.py .....                                                   [ 12%]
test_odeint.py .....                                                     [ 18%]
test_on_funcs.py ............                                            [ 33%]
test_on_funcs_ida.py ............                                        [ 48%]
test_user_return_vals_cvode.py ........................                  [ 77%]
test_user_return_vals_ida.py ..................                          [100%]

=============================== warnings summary ===============================
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
test_dae.py::TestDae::test_ida_old_api
  /nix/store/n76280az9qbrssvkyqx5zka53asdasni-python3.7-scikits.odes-2.4.0-9-g93075ae/lib/python3.7/site-packages/scikits/odes/dae.py:389: DeprecationWarning: Old api is deprecated, move to new api
    return self._integrator.init_step(t0, y0, yp0, y_ic0_retn, yp_ic0_retn)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================== 81 passed, 9 warnings in 1.31s ========================
```

**Comment by bmcage** [comment]
@aragilar I believe I have fixed all issues, tests passing, except 'extended' py37 it seems, but I cannot reproduce this error on my PC, see https://travis-ci.org/bmcage/odes/jobs/590447690. Any idea? Perhaps bad cache, but I fail in seeing in Travis sundials being build.

Default is now double precision and index type 64, the same as sundials proper, so  `-DSUNDIALS_INDEX_SIZE=32` required (or the deprecated `-DSUNDIALS_INDEX_TYPE=int32_t`) when compiling sundials to have same behavior as odes master. 

Please test with your code, so as to have as complete test as possible before release.

**Comment by bmcage** [comment]
Seg fault with extended does not happen on Ubuntu 18.04 which I use, so I cannot reproduce. 
In the tests, changed to running extended test on trusty, and allow-failure of it when not on trusty. This makes all test pass, but means when upgrading over trusty (20.04 I assume), this introduced bug will have to be found.

**Pull request merged**
