### PR TITLE
Update sundials wrapping code for multiple precisions

### PR DESCRIPTION
**Pull request by aragilar**
This adds support for building against sundials with multiple precisions. As part of this:
 * the sundials headers have been removed
 * the code in sundials_auxiliary.c has been converted to cython and put in in common_defs.pyx
 * there is now one floating point type (DTYPE_t, and associated numpy type DTYPE)
 * the setup.py in the sundials directory has been cleaned up (numpy already provides support for user defined blas/lapack path, and we don't use fortran to build), and now has support for different lib and include paths
 * travis config updated to new containers (as the old containers have been removed, breaking testing on python 3.3)

### CODE REVIEW

**Comment by bmcage** [comment]
Nice work. I'll try to go over it as soon as time permits!

**Comment by aragilar** [comment]
I forgot about the tests, the tests appear to need updating to import the correct precision, so don't merge yet.

**Comment by aragilar** [comment]
I've added testing of single and extended precision to travis, apparently numpy/cython only up-convert not down-convert, so I'll to update the tests, but once all the tests pass, this is ready to be merged.

**Comment by aragilar** [comment]
I've changed the travis config such that single precision tests can fail, I suspect we need to work out what a reasonable precision would be for the single case, but that can be done in a different PR.

**Comment by aragilar** [comment]
There's a new release of sundials which should fix the arkode problem (I'll need to test whether it's actually been fixed, which I'll do once I or someone else has time to package the new release for Debian, sundials is at 2.7 in Debian currently).

One thing I have found when building the multiple precision support is that numpy.distutils appears to have issues with configuring at sdist creation vs build time with cython, which I'll need to track down (it may be that switching to using setuptools is the solution, it's what we do in h5py to avoid this). I'll split out the c to cython stuff and do that as a separate PR, as that should be much simpler (and not need me to dig into numpy.distutils).

**Comment by aragilar** [comment]
Replaced by #59.

**Pull request closed without merging**
